### ISSUE TITLE
Dataset generation frequently hangs

### ISSUE THREAD

**Issue by alters-mit** [alters-mit/tdw_physics#18]
This has been reported by Dan Yamins and other users in his lab.

Steps to reproduce:

1. Use OS X or a Linux server (this bug doesn't seem to affect machines running Windows)
2. Run `stability.py --num 300`
3. Run build
4. Let it run for a while

Result: Controller eventually hangs at `communicate()`

I haven't yet been able to reproduce this bug. I'm using this GitHub issue to track tests.

# My tests

Each trial is 300-500 frames.

| OS | Can the controller run 300 trials _without_ hanging? |
| --- | --- |
| Windows | yes |
| Ubuntu (desktop) | yes |
| OS X | yes |

**Comment by yamins81** [comment]
I have found I can create this problem (or at least, what I think might be the same problem, at any rate) just by running the basic benchmarker:

   `python3.7 benchmarker.py --boxes --images`


However, I find that I have to let it run longer than the 10k step test in the repo; both Linux and OSX hang reliably before 50k steps, but often OSX takes longer than 20k steps.  So I've modified the benchmarker to run longer than in the master repo.

**Comment by yamins81** [comment]
Note that I have found that is useful to print out frame ID every once in a while (e.g. once every 250 frames for instance)  when running the benchmarker, so i can tell the difference between the process just taking a while and hanging.

**Comment by yamins81** [comment]
Here is the modified benchmarking code I use.  (i've renamed it to ".txt" because github won't allow me to upload a file with a .py extension, but if you want to run it, just change the extension back to .py)

[benchmarker.txt](https://github.com/alters-mit/tdw_physics/files/5984998/benchmarker.txt)

**Comment by yamins81** [comment]
I can also create the problem with my tdw_physics code.   There it takes like < 300 frames to cause the problem, and I can set up a version of it for you to replicate if you want -- maybe though we should see if fixing the problem with just the basic benchmarker solves it everywhere. It seems like a low-level socket problem or similar.    One thing that I have noticed is that  processes that communicate larger payloads need fewer frames to cause the hanging problem.  (E.g. you need 10k or more frames for the basic benchmarker to hang just sending the empty command, while for the tdw_physics controller only a few hundred frames are needed.)

**Comment by alters-mit** [comment]
I ran your benchmarker.py controller on Windows and Linux desktop and there was no hanging or freezes. We still need to test it on a Linux server and on OS X.

Your problem with tdw_physics might be a separate issue. You might be running out of disk space! Could you check if that's the case?

**Comment by instbldrjems** [comment]
I just ran Dan's benchmarker.py on OSX and it ran through to completion without errors or freezing.

So just the Linux server left to test....

**Comment by yamins81** [comment]
Hm weird.   Both I and Dan bear just ran this on our own OSX laptops and *definitely* still hangs.   Maybe I can just arrange to give you a demo over Zoom or something ... I can reproduce the problem in 3 mins.

**Comment by yamins81** [comment]
@alters-mit not running out of disk space!    hundreds of GBs available!

**Comment by danielbear** [comment]
Yes, as @yamins81 mentioned I can reproduce the problem. Running his 

```
python benchmarker.py --boxes --images
```
on OSX eventually hangs, in my case at `num_trials=9600` or so. 

I've also found that it lasts for more trials when omitting --boxes or --images, which is consistent with @yamins81 idea that larger payloads induce the problem sooner.

**Comment by alters-mit** [comment]
@yamins81 Try this:

1. Replace line 149 of the benchmarker.py script you attached to this Issue: `    b = Benchmarker(launch_build=True, check_version=False)` replace with this: `    b = Benchmarker(launch_build=True, check_version=True)`
2. Run controller on OS X
3. Post the Python console output.
4. Attach the build Player log:     https://docs.unity3d.com/Manual/LogFiles.html

**Comment by yamins81** [comment]
Ok, done.    Here's console output

Your installed version: 1.7.15 doesn't match tdw.version.__version__: 1.7.16 (this may be because you're using code from the tdw repo that is ahead of PyPi).
You are using TDW 1.7.15.0 but version 1.8.0.0 is available.
To upgrade to the last version of 1.7:
pip3 install tdw==1.7.9.2
Consider upgrading to the latest version of TDW (1.8.0):
pip3 install tdw -U
Build version 1.7.16
Unity Engine 2019.4.16f1
Python tdw module version 1.7.16
num_trials=0
num_trials=200
num_trials=400
num_trials=600
num_trials=800
.... 
[got stuck at 24800 trials this time]


Attached is player.log but renamed so github lets me attach it. 


[Player_log.txt](https://github.com/alters-mit/tdw_physics/files/5991188/Player_log.txt)

**Comment by danielbear** [comment]
I tried the same, using TDW 1.8.0. This time it hung at 25000 trials. 

Console:

```
Your installed tdw Python module is up to date with PyPi.
Build version 1.8.0
Unity Engine 2020.2.2f1
Python tdw module version 1.8.0
```

renamed log:
[Player_log.txt](https://github.com/alters-mit/tdw_physics/files/5991256/Player_log.txt)

**Comment by alters-mit** [comment]
Thanks. It looks like you're using a very old version of OpenGL. I don't know if that's relevant though.

Could you send a list of which processes are currently running on which ports? I'm not sure exactly how to do this on OS X but I'd just like to confirm that there's nothing unexpected that could be interfering with TDW.

**Comment by alters-mit** [comment]
@danielbear The player log you sent was generated by a VERY old version of TDW, not 1.8.0. There are exceptions in the log because you sent commands that haven't existed for at least a year and a half.

**Comment by danielbear** [comment]
Sorry, do you mean this 
`~/Library/Logs/MIT/TDW/Player.log`
[Player_log.txt](https://github.com/alters-mit/tdw_physics/files/5991302/Player_log.txt)

**Comment by alters-mit** [comment]
@danielbear Yes, that's the correct log. I don't see anything obviously wrong in this log.

**Comment by alters-mit** [comment]
@yamins81 I messaged you on Slack re: setting up Python 3.7 on the server. Did you see my message?

**Comment by yamins81** [comment]
@alters-mit I've noticed that when this problem with hanging occurs, it doesn't cause any log event. (whether in this benchmarker context or with tdw_physics)

**Comment by alters-mit** [comment]
@yamins81 I ran `python3 benchmarker.py --boxes --images` on your server, and it consistently hangs.

I ran `netstat -ano` and got this:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Timer
tcp        0      0 127.0.0.1:6006          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:42057           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp       32      0 10.102.2.161:52788      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp        0      0 10.102.2.161:22         171.66.24.28:60132      ESTABLISHED keepalive (6204.38/0/0)
tcp        0      0 10.102.2.161:22         171.66.24.28:60078      ESTABLISHED keepalive (6073.31/0/0)
tcp        0      0 127.0.0.1:45036         127.0.0.1:1071          TIME_WAIT   timewait (3.88/0/0)
tcp        0      0 10.102.2.161:22         10.102.2.142:34158      ESTABLISHED keepalive (5057.50/0/0)
tcp        0      0 192.168.3.101:885       192.168.3.10:2049       ESTABLISHED keepalive (57.06/0/0)
tcp        0      0 10.102.2.161:59254      10.102.2.142:4505       ESTABLISHED keepalive (9.18/0/0)
tcp       32      0 10.102.2.161:52698      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp        0    256 10.102.2.161:22         171.66.24.28:60146      ESTABLISHED on (0.20/0/0)
tcp       32      0 10.102.2.161:52700      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 :::44912                :::*                    LISTEN      off (0.00/0/0)
udp        0      0 0.0.0.0:60656           0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:631             0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           off (0.00/0/0)
udp6       0      0 :::50542                :::*                                off (0.00/0/0)
udp6       0      0 :::5353                 :::*                                off (0.00/0/0)
Active UNIX domain sockets (servers and established)
```

I'm running TDW on port 1071.

Why is there a `TIME_WAIT` on port 1071? According to [this site](https://9oelm.github.io/2018-05-06--Listening,-Established,-Close_wait-and-Time_wait-in-netstat/):

> TIME_WAIT indicates that local endpoint (this side) has closed the connection. The connection is being kept around so that any delayed packets can be matched to the connection and handled appropriately. The connections will be removed when they time out within four minutes.

**Comment by alters-mit** [comment]
If I run `netstat -ano` *while* TDW is hanging:

```

Proto Recv-Q Send-Q Local Address           Foreign Address         State       Timer
tcp        0      0 127.0.0.1:6006          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:42057           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:1071            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:53710         127.0.0.1:42310         ESTABLISHED off (0.00/0/0)
tcp        0      0 127.0.0.1:1071          127.0.0.1:45084         ESTABLISHED off (0.00/0/0)
tcp       32      0 10.102.2.161:52788      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp        0    256 10.102.2.161:22         171.66.24.28:60132      ESTABLISHED on (0.20/0/0)
tcp        0      0 127.0.0.1:39538         127.0.0.1:34158         ESTABLISHED off (0.00/0/0)
tcp        0      0 127.0.0.1:1071          127.0.0.1:45080         TIME_WAIT   timewait (18.85/0/0)
tcp        0      0 127.0.0.1:34158         127.0.0.1:39538         ESTABLISHED off (0.00/0/0)
tcp        0      0 10.102.2.161:22         171.66.24.28:60078      ESTABLISHED keepalive (5156.62/0/0)
tcp        0      0 127.0.0.1:36118         127.0.0.1:44872         ESTABLISHED off (0.00/0/0)
tcp        0      0 10.102.2.161:22         10.102.2.142:34158      ESTABLISHED keepalive (4140.81/0/0)
tcp        0      0 192.168.3.101:885       192.168.3.10:2049       ESTABLISHED keepalive (21.77/0/0)
tcp        0      0 10.102.2.161:59254      10.102.2.142:4505       ESTABLISHED keepalive (67.85/0/0)
tcp        0      0 127.0.0.1:45084         127.0.0.1:1071          ESTABLISHED off (0.00/0/0)
tcp        0      0 127.0.0.1:42310         127.0.0.1:53710         ESTABLISHED off (0.00/0/0)
tcp        0      0 127.0.0.1:44872         127.0.0.1:36118         ESTABLISHED off (0.00/0/0)
tcp       32      0 10.102.2.161:52698      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp        0      0 10.102.2.161:22         171.66.24.28:60146      ESTABLISHED keepalive (5386.00/0/0)
tcp        0      0 127.0.0.1:1071          127.0.0.1:45082         TIME_WAIT   timewait (48.99/0/0)
tcp       32      0 10.102.2.161:52700      149.154.167.220:443     CLOSE_WAIT  off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 :::44912                :::*                    LISTEN      off (0.00/0/0)
udp        0      0 0.0.0.0:60656           0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:631             0.0.0.0:*                           off (0.00/0/0)
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           off (0.00/0/0)
udp6       0      0 :::50542                :::*                                off (0.00/0/0)
udp6       0      0 :::5353                 :::*                                off (0.00/0/0)

```

I don't know enough about servers to interpret this, but it looks weird that there are several entries for port 1071!

**Comment by alters-mit** [comment]
This might be relevant: https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux

**Comment by alters-mit** [comment]
I added a few print messages to `communicate()`:

```python
from argparse import ArgumentParser
from time import time
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
import json
from typing import Union, List


"""
Use this script to benchmark TDW.
"""


class Benchmarker(Controller):
    def __init__(self, port: int = 1071, check_version: bool = True, launch_build=False):
        super().__init__(port=port, check_version=check_version, launch_build=launch_build)

    def communicate(self, commands: Union[dict, List[dict]]) -> list:
        if not isinstance(commands, list):
            commands = [commands]

        self.socket.send_multipart([json.dumps(commands).encode('utf-8')])
        print("sent")

        resp = self.socket.recv_multipart()
        print("recv")
        return resp
```

I ran the controller 3 times and it stopped at `sent` each time

**Comment by alters-mit** [comment]
I ran a "simulator" of the build:

controller_simulator.py

```python
from time import time
from tdw.controller import Controller


"""
This is a minimal controller to test network performance.
"""

if __name__ == "__main__":
    num_trials = 50000
    sizes = [1, 1000, 10000, 700000]
    c = Controller(launch_build=False, check_version=False)
    for size in sizes:
        c.communicate({"$type": "send_junk", "length": size, "frequency": "always"})
        t0 = time()
        for i in range(num_trials):
            if i % 200 == 0:
                print('num_trials=%d' % i)
            c.communicate({"$type": "do_nothing"})
        fps = (num_trials / (time() - t0))

        print(round(fps))
    c.communicate({"stop": True})
    c.socket.close()
```

build_simulator.py

```python
import zmq
from secrets import token_bytes
from json import loads


"""
This script simulates a build.
When it receives a message, the simulated build will send back a message.
This message is approximately the same size as that sent by a real TDW build.
This script is meant to be used to benchmark optimal network performance.
"""


if __name__ == "__main__":
    context = zmq.Context()

    outputs = {1: token_bytes(1),
               1000: token_bytes(1000),
               10000: token_bytes(10000),
               700000: token_bytes(700000)
               }

    # Use this socket to receive messages from the server.
    sock = context.socket(zmq.REQ)
    sock.connect("tcp://localhost:1071")

    key = 1
    done = False
    while not done:
        sock.send_multipart([outputs[key]])
        resp = loads(sock.recv_multipart()[0])[0]
        if "stop" in resp:
            done = True
        elif resp["$type"] == "send_junk":
            key = resp["length"]
```

Result: No hanging

**Comment by alters-mit** [comment]
`python3.7 --boxes --transforms` also hangs at `sent` (this benchmark doesn't include image capture)

**Comment by yamins81** [comment]
Interesting -- so what do you think the implication of these results is?  Is it like, there's a problem with zmq on on these OS builds?  Or should we look more into TIME_WAIT?  I never dealt with that parameter before.    

Or alternatively, does the fact that the build simulator doesn't hang suggest that the problem is in TDW?

**Comment by subalterngames** [comment]
OK I think I found the problem. This appears to be an inevitably issue with ZMQ's synchronous REQ-REP pattern. I modified the  netcode to close the socket and alert the controller that it needs to resend. This fixes the hanging issue!

**Build:**

```csharp
            else if (state == State.ReadyToReceive)
            {
                // Try to receive a message.
                if (!requestSocket.TryReceiveMultipartMessage(Timeout, ref output))
                {
                    Debug.Log("Timeout when trying to receive a message. Reconnecting...");
                    // Reconnect.
                    requestSocket.Close();
                    NetMQConfig.Cleanup();
                    requestSocket = new RequestSocket(NETWORK_PREFIX + address + PORT_INFIX + port.ToString());

                    // Let the controller know we failed to receive the message.
                    input.Clear();
                    // The build is expecting this message.
                    input.Append(FailedToReceive);
                    // Add a dummy frame count.
                    input.Append(0);
                    Debug.Log("...Done!");
                    state = State.ReadyToSend;
                }
                else
                {
                    // Set the state: We are ready to unpack the message.
                    state = State.ReadyToUnpack;
                }
            }
```

**Controller:**

```python
        # Send the commands.
        self.socket.send_multipart(msg)
        # Receive output data.
        resp = self.socket.recv_multipart()

        # Occasionally, the build's socket will stop receiving messages.
        # If that happens, it will close the socket, create a new socket, and send a dummy output data object.
        # The ID of the dummy object is "ftre" (FailedToReceive).
        # If the controller receives the dummy object, it should re-send its commands.
        # The dummy object is always in an array: [ftre, 0] 
        # This way, the controller can easily differentiate it from a response that just has the frame count.
        while len(resp) > 1 and OutputData.get_data_type_id(resp[0]) == "ftre":
            self.socket.send_multipart(msg)
            resp = self.socket.recv_multipart()
```

**Comment by alters-mit** [comment]
@yamins81 

Try this test on a Linux server:

- Install the `tdw` module from the repo and checkout to the correct branch (you might be able to skip some of these steps):
  - `pip3 uninstall tdw`
  - `git clone https://github.com/threedworld-mit/tdw.git`
  - `cd tdw`
  - `git checkout req_freeze`
  - `pip3 install -e .`
- `cd Python/benchmarking`
- `python3.7 benchmarker.py --boxes --images` (this will print the number of trials per 200)

In another shell:
- `wget https://github.com/threedworld-mit/tdw/releases/download/req_freeze/TDW_Linux.tar.gz`
- `tar -xf TDW_Linux.tar.gz`
- `cd TDW`
- `DISPLAY=:0.0 ./TDW.x86_64`

Result: The benchmark will run to completion, occasionally pausing for a few seconds while it times out.

Let me know if that works!

**Comment by danielbear** [comment]
@alters-mit 

I just tried this and it works! Completed 50000 trials. Thank you, Seth.

Could this fix be applied to the OSX build as well?

**Comment by alters-mit** [comment]
@danielbear 

It ought to be applicable to OS X, yes. Please run the following tests:

1. **Run the same test listed above but on OS X**

Result: Same behavior as on the Linux server (the controller completes 50K trials)

Use this build: https://github.com/threedworld-mit/tdw/releases/download/req_freeze/TDW_OSX.tar.gz

2. **On a remote server, test tdw_physics**

- `cd path/to/tdw_physics`
- `git pull` (update to the latest version)
- `cd controllers`
- `python3.7 stability.py`

In another shell:

- Run build (follow the instructions I posted in my previous comment on this thread)

**Comment by danielbear** [comment]
@alters-mit 

Both tests passed. OSX runs 50000 trials, and I seem to be able to run as many tdw_physics trials as needed without hanging.

Thanks!

**Comment by alters-mit** [comment]
@yamins81 @danielbear 

Great!! Closing this ticket.

I've updated TDW to v1.8.1, which includes the bug fix. You should do the following:

1. Get the latest TDW build: https://github.com/threedworld-mit/tdw/releases/latest/
2. Update your `tdw` module:

- `cd path/to/tdw`
- `git fetch`
- `git checkout master`
- `git pull`

Or:

- `pip3 uninstall tdw`
- `pip3 install tdw`

**Comment by yamins81** [comment]
Excellent!!! Thanks so much for taking care of this.
