### ISSUE TITLE
Frictional effects are non-physically strong

### ISSUE THREAD

**Issue by danielbear** [alters-mit/tdw_physics#23]
Frictional effects on rolling/sliding objects appear unnaturally strong, such that rolling/sliding objects' momenta are too much and too quickly reduced. 

The expected behavior of having a ball move down a ramp, where both objects have nonzero friction, is that friction will cause the ball to *roll* rather than *slide*, and the ball will leave the ramp with nonzero momentum (in proportion to its mass, the ramp height, and rotational moment of inertia.) 

Instead, a ball appears to slow down as it reaches the end of the ramp and even stop before exiting. If both objects have `static_friction` and `dynamic_friction` set to `0.0`, the ball will gain momentum as expected but will do so by _sliding_, not rolling (which is physically correct, but visually unusual -- even a little friction should cause rolling.) 

I wondered whether this could be fixed by changing the `collision_detection_mode` of the ramp, setting it to be a `kinematic_object`, or giving the ball a much larger `mass`. However, none of these attempts changed the behavior seen below.

`ramp has nonzero friction`
https://user-images.githubusercontent.com/3999333/111195671-dfb78d80-8592-11eb-82d8-99ab17f0378b.mp4
https://user-images.githubusercontent.com/3999333/111196953-41c4c280-8594-11eb-988b-c9a1e44865f8.mp4

`ramp has zero friction`
https://user-images.githubusercontent.com/3999333/111195924-24dbbf80-8593-11eb-9a5d-556c84a5f746.mp4

**Comment by alters-mit** [comment]
@danielbear 

I get reasonable behavior with this controller. To make the ball spin instead of slide, I set the direction of the force to include a downward y component. I also found that setting a higher mass for the ball makes the movement more realistic because it has more momentum.

- Does the behavior in my controller seem reasonable to you?
- If you rewrite your controller to be more like mine, do you get reasonable behavior?

```python
from typing import List
from tdw.tdw_utils import TDWUtils
from tdw.librarian import ModelLibrarian
from tdw_physics.rigidbodies_dataset import RigidbodiesDataset


class Ramp(RigidbodiesDataset):
    def __init__(self, port: int = 1071):
        super().__init__(port=port)
        self.ball_record = ModelLibrarian("models_flex.json").get_record("sphere")
        self.ramp_record = ModelLibrarian("models_full.json").get_record("ramp_with_platform_60")
        self.pin_record = ModelLibrarian("models_flex.json").get_record("cylinder")
        self.ball_material = "marble_white"
        self.start()

    def get_trial_initialization_commands(self) -> List[dict]:
        ball_id = self.get_unique_id()
        commands = []
        # Add the ramp.
        ramp_id = self.get_unique_id()
        commands.extend(self.add_physics_object(record=self.ramp_record,
                                                o_id=ramp_id,
                                                position=TDWUtils.VECTOR3_ZERO,
                                                rotation=TDWUtils.VECTOR3_ZERO,
                                                mass=1000,
                                                bounciness=0.1,
                                                static_friction=0.1,
                                                dynamic_friction=0.1))
        # Make the ramp kinematic.
        commands.append({"$type": "set_kinematic_state",
                         "id": ramp_id,
                         "is_kinematic": True,
                         "use_gravity": False})
        # Add the pin.
        pin_id = self.get_unique_id()
        commands.extend(self.add_physics_object(record=self.pin_record,
                                                position={"x": -1.69, "y": 0, "z": 0},
                                                rotation=TDWUtils.VECTOR3_ZERO,
                                                mass=1,
                                                dynamic_friction=0.5,
                                                static_friction=0.3,
                                                bounciness=0.8,
                                                o_id=pin_id))
        commands.append({"$type": "scale_object",
                          "id": pin_id,
                          "scale_factor": {"x": 0.2, "y": 0.7, "z": 0.2}})
        # Add the ball.
        commands.extend(self.add_physics_object(record=self.ball_record,
                                                position={"x": 1.29, "y": 1.001, "z": 0},
                                                rotation=TDWUtils.VECTOR3_ZERO,
                                                mass=1,
                                                dynamic_friction=0.1,
                                                static_friction=0.1,
                                                bounciness=0.6,
                                                o_id=ball_id))
        # Make the ball smaller. Set the ball's visual material. Apply a force. Move the camera.
        commands.extend([{"$type": "scale_object",
                          "id": ball_id,
                          "scale_factor": {"x": 0.3, "y": 0.3, "z": 0.3}},
                         self.get_add_material(material_name=self.ball_material, library="materials_low.json"),
                         {"$type": "set_visual_material",
                          "id": ball_id,
                          "material_name": self.ball_material,
                          "object_name": "sphere",
                          "material_index": 0},
                         {"$type": "set_mass",
                          "mass": 10,
                          "id": ball_id},
                         {"$type": "apply_force_to_object",
                          "id": ball_id,
                          "force": {"x": -3, "y": -1, "z": 0}},
                         {"$type": "teleport_avatar_to",
                          "position": {"x": -4.438, "y": 1.926, "z": -4.244}},
                         {"$type": "look_at_position",
                          "position": TDWUtils.VECTOR3_ZERO}])
        return commands

    def get_per_frame_commands(self, resp: List[bytes], frame: int) -> List[dict]:
        return []

    def is_done(self, resp: List[bytes], frame: int) -> bool:
        return frame > 500

    def get_field_of_view(self) -> float:
        return 55

    def get_scene_initialization_commands(self) -> List[dict]:
        return [{"$type": "load_scene",
                 "scene_name": "ProcGenScene"},
                TDWUtils.create_empty_room(12, 12)]


if __name__ == "__main__":
    c = Ramp()
    c.run(num=10, output_dir="D:/ramp", temp_path="D:/temp.hdf5", width=256, height=256)
```

**Comment by danielbear** [comment]
Thanks for creating this test controller. Your controller's behavior seems reasonable, and by comparing to mine + running a bunch of experiments I think:

1. Things basically look right if the friction (esp. dynamic) on the `ramp` is low, `~0.1`
2. If the friction on the ramp is higher, `~0.5`, the effects appear to be too strong: a ball will exit the ramp with little to no momentum, despite looking like it's rolling. (Examples below.) 

In reality, the frictional damping on a rolling object is much lower than on a sliding object. My guess as to what's happening is that even when it _looks_ like the ball is rolling down the ramp and not sliding, PhysEx thinks it's sliding and is applying more friction than it should -- which leads to what looks like more loss of momentum than there should be, even for a ramp with higher coefficient of friction. 

It's hard to say exactly what the behavior should be, but in any case I think we can get around this issue by just setting the ramp frictional coefficient to a lower value, as you did in your controller.

`friction = 0.1`
https://user-images.githubusercontent.com/3999333/111522998-2e9b2980-8731-11eb-990a-d5ba783d2da7.mp4
https://user-images.githubusercontent.com/3999333/111523230-6c984d80-8731-11eb-8ead-7394382eebb9.mp4

`friction = 0.5`
https://user-images.githubusercontent.com/3999333/111523170-57bbba00-8731-11eb-8de5-ed9f4a76bc11.mp4
https://user-images.githubusercontent.com/3999333/111523284-7c179680-8731-11eb-9a4d-09a33f771ac3.mp4
